Ù name: learn_with_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  
  cupertino_icons: ^1.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
      - assets/images/
  fonts:
      - family: Viga
        fonts:
          - asset: assets/fonts/Viga-Regular.ttf

